### ISSUE TITLE
The paid amount (20) and order total (20) did not match

### ISSUE THREAD

**Issue by stianmandarin** [superbigco/craft-vipps#40]
**Bug / steps / expected behaviour**
Production keys are set. Trying to do a real payment. The Vipps app pops up on my phone, and the app reports that the payment went through. Commerce let's me capture the amount, but nothing ever shows up in my Vipps account. Below is what I find weird from the log.

Idea on what's happening here? See vipps.log

```
2020-12-21 15:47:21 [][][info] The paid amount (20) and order total (20) did not match. There was a discrepancy of 0
2020-12-21 15:47:21 [][][info] The discrepancy is below 0.10 - setting transaction to order total.
```

**Additional info**
- Craft version: 3.5.17.1
- PHP version: 7.1.33
- Database driver & version: MySQL 10.3.27 
- Plugin version: 1.0.6

**Comment by sjelfull** [comment]
Did you figure this out?

I've currently on holiday, but will try to help you if I can.

**Comment by stianmandarin** [comment]
> Did you figure this out?
> 
> I've currently on holiday, but will try to help you if I can.

It's sorted 👍
