### ISSUE TITLE
Plugin uses deprecated function `Order::getAvailableShippingMethods()`

### ISSUE THREAD

**Issue by nmenglund** [superbigco/craft-vipps#41]
**Describe the bug**
The plugin uses the deprecated function `Order::getAvailableShippingMethods()` according to the Craft
deprecation warnings:

_Order::getAvailableShippingMethods() has been deprecated. Use Order::getAvailableShippingMethodOptions()._

The source is `vendor/superbig/craft-vipps/src/controllers/CallbackController.php:286`.

**Expected behavior**
No deprecation warnings from the plugin.

**Additional info**
- Craft version: 3.6.6
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Commerce 3.2.14.1, Vipps 1.0.6

**Comment by sjelfull** [comment]
Thanks for reporting, will release a fix soon.
