### ISSUE TITLE
Race condition between Vipps and user browser can cause user to receive `{"status":true}` JSON in browser

### ISSUE THREAD

**Issue by nmenglund** [superbigco/craft-vipps#42]
**Describe the bug**
If Vipps triggers the `complete` endpoint before the user has triggered the `return` endpoint on their return from Vipps, the order is already marked as paid, and the function returns early with a JSON response instead of the expected order confirmation. See https://github.com/superbigco/craft-vipps/blob/master/src/controllers/CallbackController.php#L76

**Expected behavior**
Regardless of which endpoint is reached first, the user should get a consistent experience: a redirect to the fallback URL.

**Additional info**
- Craft version: 3.6.6
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Vipps 1.0.6, Commerce 3.2.15.2

**Comment by sjelfull** [comment]
This is fixed in a upcoming release.
